#ifndef TEST_INTEROP_CXX_TEMPLATES_INPUTS_USING_DIRECTIVE_H
#define TEST_INTEROP_CXX_TEMPLATES_INPUTS_USING_DIRECTIVE_H

#include <string>

typedef std::string MyString;

#endif // TEST_INTEROP_CXX_TEMPLATES_INPUTS_USING_DIRECTIVE_H
